FROM python:3.9-slim

# Cài đặt Chrome và các công cụ cần thiết
RUN apt-get update && apt-get install -y \
    google-chrome-stable \
    wget \
    unzip && \
    rm -rf /var/lib/apt/lists/*

# Cài đặt các thư viện Python
COPY requirements.txt /app/requirements.txt
WORKDIR /app
RUN pip install -r requirements.txt

# Copy mã nguồn
COPY . /app

# Chạy ứng dụng
CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:5000", "app:app"]